### PR TITLE
Backport llvm & add seccomp

### PR DESCRIPTION
**Pull request by Herrie82**

### CODE REVIEW

**Comment by Herrie82** [comment]
@shr-project I just took from meta-virtualisation kirkstone branch which didn't have the Upstream-Status (except for the CVE). Added it back now. Sorry for the oversight, need more coffee :)

**Review by shr-project — APPROVED** [review]

**Comment by shr-project** [comment]
> @shr-project I just took from meta-virtualisation kirkstone branch which didn't have the Upstream-Status (except for the CVE). Added it back now. Sorry for the oversight, need more coffee :)

yeah, I've checked meta-virt and Upstream-Status to all the patches was added only after lxc-5 upgrade.

**Comment by Herrie82** [comment]
I could test LXC 5 as well. Shouldn't take too long

**Comment by Herrie82** [comment]
Let's keep LXC5 out for now, since it could possibly break Halium targets.

**Pull request merged**
