### PR TITLE
meta-webos-ports: Update classes with info from webOS OSE

### PR DESCRIPTION
**Pull request by Herrie82**
* webOS OSE introduced quite some classes in it's recipes. Add them here already.
* Update already existing classes where needed.
* Delete now obsolete webos_system_bus_paths since these are now incorporated in webos_filesystem_paths.
* Delete references to webos_system_bus_paths.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by shr-project** [comment]
Please don't add classes which aren't used anywhere (they are IMHO pretty useless for us).

**Comment by Herrie82** [comment]
@shr-project I just added them, but can clean up if you prefer. 

Based on review: 

webos_pmlog_config.bbclass: Add flag to recipe instead?

webos_prerelease_dep.bbclass: Empty, delete? 
webos_fs_layout.bbclass: Commented out, delete? 
webos_upstream_from_repo.bbclass: Delete, same as webos_component.bbclass, use that one instead where needed.

webos_program.bbclass, webos_library.bbclass & webos_daemon.bbclass: Delete because only inherits webos_pkgconfig.bbclass

**Comment by shr-project** [comment]
Most of these were intentionally removed by me in meta-webos-ports few years back:

commit b8ee39ef02aea02047749bed776b332f9d8d7359
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Thu Dec 11 21:14:29 2014 +0100

    classes: Eliminate webos_component, webos_fs_layout, webos_upstream*
    
    * change default WEBOS_SYSTEM_BUS_SKIP_DO_TASKS to 1
    
    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit e5a53a3a115fd40ea764a67269a089813ea5e55a
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Thu Dec 11 21:07:44 2014 +0100

    recipes: Inherit allarch instead of webos_arch_indep
    
    * allarch is good enough
    
    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

commit 3bfab75db901cf2124ed070e524f97160dc8c313
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Thu Dec 11 21:06:23 2014 +0100

    recipes: eliminate inherit for pkgconfig and library, daemon, program classification
    
    * they all just inherit pkgconfig and weren't used for anything else
    
    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

**Comment by Herrie82** [comment]
@shr-project Updated it to reflect your suggestions. So the stuff that was previously deleted by you doesn't appear in this PR anymore.

**Pull request merged**
