### PR TITLE
Migrate from Mer to Sailfish (https://forum.sailfishos.org/t/changes-…

### PR DESCRIPTION
**Pull request by NuclearKev**
…needed-to-merge-the-project-names-to-sailfish-os/1672)

### CODE REVIEW

**Comment by shr-project** [comment]
Thanks!
;protocol=https will be needed in other SRC_URIs now as well, I will add it when cherry-picking this to all active branches.

**Comment by shr-project** [comment]
Extended to cover more recipes and applied to all active branches:
   385fd42c7..ef8c22d4e  hardknott -> hardknott
   09e034198..a61ab3a40  honister -> honister
   88b16bbaf..98bfedff1  master -> master

**Comment by NuclearKev** [comment]
It appears there are more that I didn't know of. If needed, I can create another PR with those.

**Comment by shr-project** [comment]
> It appears there are more that I didn't know of.

I think I've fixed them all, make sure to use latest hardknott branch.

**Pull request closed without merging**
