### PR TITLE
nyx-conf: Add gpsConfig.conf

### PR DESCRIPTION
**Pull request by Herrie82**
We need a device specific configuration file for GPS, instead of having it provided by com.webos.service.location, have it provided by nyx-conf which is any way MACHINE_ARCH already.

### CODE REVIEW

**Comment by Herrie82** [comment]
@Tofee @shr-project 

Any thoughts on this? This way we can provide a MACHINE specific GPS config file and we can keep com.webos.service.location generic per ARCH.

**Comment by Tofee** [comment]
Agreed, though it would maybe be best to remove the file using a patch?

**Comment by Herrie82** [comment]
@Tofee Happy to do it that way. @shr-project Any thoughts?

**Comment by Herrie82** [comment]
@Tofee @shr-project Added a commit to do that. Let me know your thoughts

**Review by Tofee — APPROVED** [review]
Lgtm !

**Pull request merged**
