### PR TITLE
libcamera: replace .bb with .bbappend adding pinephone specific patch

### PR DESCRIPTION
**Pull request by shr-project**
* https://gitlab.com/MartijnBraam/libcamera/-/commits/feature/pinephone/ was last updated 3 years ago and doesn't seem to be upstreamed to libcamera

* add 4 more commits from this branch and rebase on recent libcamera release and append it only for pinephone

* the old version we had here was breaking pipewire builds as reported in: https://lists.openembedded.org/g/openembedded-devel/message/101593

* meta-oe recipe has 0.0.1 release since: https://github.com/openembedded/meta-openembedded/commit/1032bce77885f20afb40fff4ed430167c75db59b our PV said newer 0.1.0, but that was just wrong, it was 3266 commits behind v0.0.1 tag

  $ git log --oneline origin/feature/pinephone..v0.0.1  | wc -l 3266

### CODE REVIEW

**Comment by Tofee** [comment]
Well, that looks good, I'll just have to build/test it a little bit

**Comment by Tofee** [comment]
I had issues with the patch from "master" not applying on top of v0.0.1, which is a bit weird. On v0.0.4 it works well though.
On v0.0.4, the "simple" libcamera driver has been moved to the "simple" subfolder https://git.libcamera.org/libcamera/libcamera.git/tree/src/libcamera/pipeline/simple/simple.cpp?h=v0.0.4 , and I think it's quite up to date. So the bbappend might not be needed at all.
At runtime, it doesn't look like any camera is detected on my pinephone
However, as the camera support isn't really back yet in latest luneos builds, we might as well just drop our current libcamera bbappend for the moment.

**Comment by shr-project** [comment]
> However, as the camera support isn't really back yet in latest luneos builds, we might as well just drop our current libcamera bbappend for the moment.

You mean libcamera recipe, right? Or do you want me to apply this PR and then delete it completely?

Both are fine with me :).

**Comment by Tofee** [comment]
> You mean libcamera recipe, right? Or do you want me to apply this PR and then delete it completely?
> 
> Both are fine with me :).

Right, what I mean is delete our old libcamera recipe in meta-webos-ports like for your PR, but do not bother with a bbappend

**Comment by shr-project** [comment]
Removed from all 3 branches.

**Pull request closed without merging**
