### PR TITLE
luneos-default-wallpapers: install images in datadir

### PR DESCRIPTION
**Pull request by Tofee**
Signed-off-by: Christophe Chapuis <chris.chapuis@gmail.com>

### CODE REVIEW

**Comment by Tofee** [comment]
This PR would need to be tested on our targets first

**Review by shr-project — APPROVED** [review]

**Comment by Herrie82** [comment]
I'm pretty sure we need to update something else for this to work. My gut feeling says luna-init, will have a look tomorrow while traveling back

**Comment by Herrie82** [comment]
At least this one, but I'm sure there's more: https://github.com/webOS-ports/luna-init/commit/dac326d524fe806843c1d2d802419d2d1f448c06

**Comment by shr-project** [comment]
Merged to other branches as well:
  07b114e70..9d91bcf51  hardknott -> hardknott
  25d828019..5fa03ff04  master -> master

**Pull request merged**
