### PR TITLE
webruntime: upgrade to submissions/28 and drop upstreamed patches

### PR DESCRIPTION
**Pull request by shr-project**
* on gentoo with gcc-13 on host there is one more issue with dev-cpp/abseil-cpp-20230125.2 while older dev-cpp/abseil-cpp-20220623.1 works fine when building host's flatbuffers, similar to: https://github.com/protocolbuffers/protobuf/issues/10768

### CODE REVIEW

**Review by Tofee — APPROVED** [review]
That's a welcome cleanup in the patches' list, and looks good to me!

**Comment by shr-project** [comment]
I haven't checked on any target, just build tested with Nanbield and still looking at that abseil issue from host.

**Comment by Tofee** [comment]
Ok, I'll check on pinephone and qemu-x64

**Comment by Tofee** [comment]
> I now tested qemux86-64, and I saw no regression

I also validate the PR on pinephone. For me it's good to go. @Herrie82  ?

**Pull request merged**
