### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by Herrie82**
- Split meta-webos into meta-webos-ose and meta-webos-owo. 
- Move LuneOS recipes into meta-luneos
- Remove no longer needed bits such as luna-next(-conf) and luna-webkit-api

### CODE REVIEW

**Comment by Herrie82** [comment]
@shr-project Build & runtime tested for qemux86-64

**Comment by Herrie82** [comment]
@tofee This one might look huge, but it's mainly moving things into meta-webos-ose and meta-webos-owo and some recipes to meta-luneos that belong there (luna-appmanager, nyx-conf, nyx-modules-hybris for example). 

And I deleted some things no longer needed/used like luna-next stuff, luna-webkit-api etc.

**Comment by Tofee** [comment]
Looks fine to me; destination is the master branch, isn't it?

**Comment by Herrie82** [comment]
@tofee Yes master. I could do the same for Kirkstone (would mean a bit of rework due to changes in master), but I think @shr-project wasn't a big fan of pushing more to Kirkstone. Anyway the whole process takes me 10 minutes or so, so happy to also send it to Kirkstone as well

**Comment by Tofee** [comment]
@Herrie82 yes, master is better :) At first I didn't see that it targeted master, and I thought that maybe @shr-project would want to delay that one a bit.
But for master it's all good, I'll merge that now.

**Comment by Herrie82** [comment]
@Tofee Maybe wait for @shr-project feedback?

**Comment by Herrie82** [comment]
@shr-project Reworded the commit and pushed it. Did the same changes for Nanbield & Kirkstone.

**Pull request merged**
