### PR TITLE
systemd, PulseAudio: Downgrade to Fido versions

### PR DESCRIPTION
**Pull request by Herrie82**
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by shr-project** [comment]
I think we need only the main systemd recipe, not the serialgetty and native one, can you retest with only target systemd downgraded?

If it fails then it would be good indication that something else is broken.

**Comment by Herrie82** [comment]
OK my Mako is broken for now, but asked Tofe to test the image I build with these changes.

**Comment by Herrie82** [comment]
Tested & booting on Mako now.

**Comment by shr-project** [comment]
Squash 2nd and 3rd commit and add at least short explanation in commit message why we're downgrading these 2. We both remember now, but ..

**Pull request closed without merging**
