### PR TITLE
pulseaudio-distro-conf: remove alsa-ucm2 files

### PR DESCRIPTION
**Pull request by shr-project**
* https://github.com/webOS-ports/meta-webos-ports/commit/61143a41d8156449dba3a7dabd28b56446b2b07c now causes conflict between pulseaudio-distro-conf and alsa-ucm-conf:

check_data_file_clashes: Package pulseaudio-distro-conf wants to install file /OE/build/luneos-nanbield/webos-ports/tmp-glibc/work/pinephone-webos-linux/luneos-dev-image/1.0-r0/rootfs/usr/share/alsa/ucm2/conf.d/simple-card/PinePhone.conf But that file is already provided by package * alsa-ucm-conf

as PinePhone support was added in alsa-conf-ucm v1.2.9 with https://github.com/alsa-project/alsa-ucm-conf/commit/93d514761c699028fd2e8c8da86901cf21725b8b

Which package should own /usr/share/alsa/ucm2/conf.d/simple-card/PinePhone.conf? I guess alsa-conf-ucm

### CODE REVIEW

**Comment by Herrie82** [comment]
@shr-project It seems upstream only carries PinePhone (A64 chipset) not the PinePhonePro (RK3399 chipset). So we should only be deleting the PinePhone (A64) files here?

**Comment by shr-project** [comment]
I haven't tried on PPP, but looks like those files should be moved from
pulseaudio-distro-conf to alsa-ucm-conf recipes and possibly submitted
upstream for review as well by someone who cares about PPP.

**Comment by shr-project** [comment]
This might be still very broken (as I didn't look how ucm2 includes those other .conf files - as relative path from where?). I don't have any of the Pine* devices, so I won't be able to test in runtime anyway.

**Comment by shr-project** [comment]
Merged

**Pull request closed without merging**
