### PR TITLE
luna-webappmanager: bump SRCREV

### PR DESCRIPTION
**Pull request by Garfonso**

### CODE REVIEW

**Comment by morphis** [comment]
Can you add a short comment to the commit what has changed?

**Comment by Garfonso** [comment]
Uhm. To the commit? I'll try.

**Comment by Garfonso** [comment]
Don't exactly know what happened, but I think you should be able to cherry pick the right commit, right? :)

**Comment by morphis** [comment]
Yeah. Let me sort this.

**Pull request closed without merging**
