### PR TITLE
Update various components to latest version from upstream

### PR DESCRIPTION
**Pull request by Herrie82**
mobile-broadband-providers-info: Bump SRCREV
lxc: Update to 2.0.5
libhybris: Update to latest from upstream
c-ares: Update to 1.11.0
https-everywhere: Update to latest
hunspell-dictionaries: Update to latest
hunspell: Update to 1.4.1
python-tz-native: Update to 2016.7
uriparser: Update to 0.8.4 

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by shr-project** [comment]
Better, what about updating c-ares to 1.12.0 just by dropping it from our layer?

there is newer one in meta-networking already:
./meta-networking/recipes-support/c-ares/c-ares_1.12.0.bb

**Comment by Herrie82** [comment]
Krogoth only has 1.11.0 as well. But we could drop it from here I guess anyway. Prefer to use the one from meta-networking :) You want me to add a commit to drop it?

**Comment by shr-project** [comment]
> You want me to add a commit to drop it?

Ideally replace the one where you upgraded it with a drop, by git rebase -i :)

**Comment by Herrie82** [comment]
Learned something new today :) Updated :)

**Pull request merged**
